### ISSUE TITLE
PDF version

### ISSUE THREAD

**Issue by q-wertz** [hackclub/putting-the-you-in-cpu#11]
Thanks for this awesome source of information.

Do you think it is feasible to also "release" a PDF version of it?

**Comment by kognise** [comment]
I definitely want to make a one-pager view that can be easily print-to-PDFed. There's already a pretty good print stylesheet.

**Comment by q-wertz** [comment]
Nice :) Thanks.

A one-pager viewer and print to PDF would be sufficient (at least for me). Saves the time of going through all and merging the separate PDFs later.

pipeline with automated PDFs would be the icing on the cake.

**Comment by kognise** [comment]
I am working on a single-page and PDF version on https://github.com/hackclub/putting-the-you-in-cpu/tree/print-layout! Should be merged very soon. Eventually I'll make an Astro plugin to generate the PDF automatically during build.

**Comment by kognise** [comment]
https://cpu.land/editions/printable.pdf

**Comment by ekoome** [comment]
That you for the pdf version. Is it possible to add bookmarks to help jump to specific topics / table of contents. Thank you.
