### ISSUE TITLE
Configure DNS with hackclub/dns

### ISSUE THREAD

**Issue by zachlatta** [hackclub/putting-the-you-in-cpu#12]
Right now cpu.land is has DNS managed using the bank@hackclub.com Google Domains account. We want to switch this to having DNS managed using https://github.com/hackclub/dns.

Here are the steps to do that:

1. Share the domain with zach@hackclub.com on Google Domains (this is not required for `hackclub/dns`, just so I have access too)
2. Set up DNSimple to manage cpu.land's records (credentials in 1Password)
3. Set up `hackclub/dns` to use the DNSimple API to manage the domain using OctoDNS. 90% of the work should already be done, just look at how other Hack Club domains are managed in that repo.

Thank you!!

**Comment by kognise** [comment]
Done! https://github.com/hackclub/dns/commit/12b284fb8235791cc604b0ffba1639977f22cb57
