### ISSUE TITLE
Mismatched lines and line numbers on mobile

### ISSUE THREAD

**Issue by ZPedro** [hackclub/putting-the-you-in-cpu#39]
![0B2207A2-63AE-482F-8B21-23327378D77A](https://github.com/hackclub/putting-the-you-in-cpu/assets/1637791/cea60535-fc99-4661-9ec1-a18d4993a6e6)

I would describe more, but I don’t know what to tell beyond the title.

iPhone 12 mini, in case that matters.

**Comment by kognise** [comment]
jesus christ safari

**Comment by kognise** [comment]
Thanks for the bug report! Fixed :)

**Comment by ZPedro** [comment]
Confirmed fixed on my end.
