### ISSUE TITLE
Is this correct?

### ISSUE THREAD

**Issue by zarakshR** [hackclub/putting-the-you-in-cpu#7]
The [chapter on multitasking](https://cpu.land/slice-dat-time) says -

"The target latency should be equal to the time it takes for a process to resume execution after being preempted."

Is this correct? AFAIK the target latency only needs to be _atleast_ as long as the time it takes for a process to resume execution after being preempted.

**Comment by kognise** [comment]
I believe it is correct, but phrased somewhat ambiguously.

I updated this section to the following:

> A slight improvement to fixed timeslice scheduling is to pick a *target latency* — the ideal longest time for a process to respond. The target latency is the time it takes for a process to resume execution after being preempted, assuming a reasonable number of processes. *This is pretty hard to visualize! Don't worry, a diagram is coming soon.*
> 
> Timeslices are calculated by dividing the target latency by the total number of tasks; this is better than fixed timeslice scheduling because it eliminates wasteful task switching with fewer processes. With a target latency of 15&nbsp;ms and 10 processes, each process would get 15/10 or 1.5&nbsp;ms to run. With only 3 processes, each process gets a longer 5&nbsp;ms timeslice while still hitting the target latency.
> 
> Process switching is computationally expensive because it requires saving the entire state of the current program and restoring a different one. Past a certain point, too small a timeslice can result in performance problems with processes switching too rapidly. It's common to give the timeslice duration a lower bound (*minimum granularity*). This does mean that the target latency is exceeded when there are enough processes for the minimum granularity to take effect.
> 
> At the time of writing this article, Linux's scheduler uses a target latency of 6&nbsp;ms and a minimum granularity of 0.75&nbsp;ms.
> 
> <img src='https://cpu.land/images/linux-scheduler-target-latency.png' loading='lazy' alt='A diagram titled "Naive Dynamic Timeslice Round-Robin Scheduling." It depicts a time series of 3 different processes getting time to execute in a repeated cycle. In between the execution blocks of each process is a much shorter block labeled "kernel scheduler." The length of each program execution block is labeled "timeslice (2ms)." The distance from the start of process 1 executing to the next start of process 1 executing, encompassing the execution time of processes 2 and 3, is labeled as "target latency (6ms)."' width='500' />

Is this easier to understand, or is there still a technical problem?

**Comment by rishitc** [comment]
Hi @kognise,
I was reading the updated version of this section a few days ago, and I think there is still a technical problem with the wording for this section, particularly with this statement:
> The target latency is the time it takes for a process to resume execution after being preempted, assuming a reasonable number of processes.

According to this statement, the target latency should be measured **_after_** a process has been preempted until it resumes execution.

However, this is inconsistent with [your image](https://cpu.land/images/linux-scheduler-target-latency.png), where, given a process, we measure target latency from the time the process _(say, `Process 1`)_ starts execution until it resumes execution again.

I think a simple and technically correct wording should be:
> The target latency is the time it takes for all processes to complete one timeslice for execution on the CPU.

*References:*
1. https://stackoverflow.com/questions/21391176/linux-kernel-targeted-latency-vs-minimum-granularity
2. https://opensource.com/article/19/2/fair-scheduling-linux#:~:text=The%20CFS%20scheduler%20has%20a%20target%20latency%2C%20which%20is%20the%20minimum%20amount%20of%20time%E2%80%94idealized%20to%20an%20infinitely%20small%20duration%E2%80%94required%20for%20every%20runnable%20task%20to%20get%20at%20least%20one%20turn%20on%20the%20processor.
1.
