### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by szepeviktor** [hackclub/putting-the-you-in-cpu#8]
Found a misspelling: "continous" here: https://github.com/search?q=repo%3Ahackclub%2Fputting-the-you-in-cpu%20continous&type=code

**Comment by kognise** [comment]
Wow, how did you even find that? Just searching for common typos? Anywho, fixed!

**Comment by szepeviktor** [comment]
There is a tool called https://github.com/crate-ci/typos
